### ISSUE TITLE
Update to 1.20.1 Please

### ISSUE THREAD

**Issue by sternschnaube** [nad2040/Elytra-Bombing-Mod#4]
Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.minecraft.class_2338.<init>(net.minecraft.class_243)'
        at net.minecraft.class_1792.handler$zkg000$elytrabombing$use(class_1792.java:1070) ~[server-intermediary.jar:?]
        at net.minecraft.class_1792.method_7836(class_1792.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_1799.method_7913(class_1799.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14256(class_3225.java:290) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12065(class_3244.java:1177) ~[server-intermediary.jar:?]
        at net.minecraft.class_2886.method_12550(class_2886.java:29) ~[server-intermediary.jar:?]
        at net.minecraft.class_2886.method_11054(class_2886.java:7) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zdk000$carpet$modifiedRunLoop(MinecraftServer.java:5951) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

**Comment by nad2040** [comment]
Can you see if the new release I made yesterday worked? Thanks.

**Comment by sternschnaube** [comment]
I will check it later 😊

**Comment by sternschnaube** [comment]
Sorry for the late answer.
I was checking everything right now.
Anvil and TNT works fine.

But - it's possible to make just right click with the flint and steel to spam unlimited amounts of TNT.
You don't even have the need for TNT in your inventory for this.

**Comment by nad2040** [comment]
ok i think everything should be fixed

**Comment by sternschnaube** [comment]
Thank you, I will check the mod later 😊
